- name: Reboot my servers
  hosts: all
  become: yes

- tasks:
  - name: Reboot
    shell: sleep 3 && reboot now
    async: 1
    poll: 0
    when: {{ todo }} == 'reboot'

  - name: Shutdown
    shell: sleep 3 && shutdown now
    async: 1
    poll: 0
    when: {{ todo }} == 'shutdown'